# Generated by Django 4.2.8 on 2023-12-04 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('password', models.CharField(blank=True, max_length=20, verbose_name='Пароль')),
                ('birth_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата рождения')),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], default='M', max_length=5)),
                ('physical_activity', models.CharField(choices=[('VL', 'Очень низкая физическая активность'), ('L', 'Низкая физическая активность'), ('A', 'Средняя физическая активность'), ('H', 'Высокая физическая активность'), ('VH', 'Очень высокая физическая активность')], default='VL', max_length=9)),
                ('target', models.CharField(choices=[('LWeight', 'Похудеть'), ('MWeight', 'Поддерживать вес'), ('GWeight', 'Набрать вес')], default='LWeight', max_length=15)),
            ],
        ),
    ]
