# Generated by Django 5.0 on 2023-12-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='grams',
            field=models.FloatField(blank=True, verbose_name='Граммовки этого продукта'),
        ),
    ]
