# Generated by Django 4.2.8 on 2023-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Название продукта')),
                ('proteins', models.FloatField(blank=True, verbose_name='Белки')),
                ('fats', models.FloatField(blank=True, verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(blank=True, verbose_name='Углеводы')),
                ('calories', models.FloatField(blank=True, verbose_name='Калории')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MAN', 'Мужчина'), ('WOMAN', 'Женщина')], default='MAN', max_length=5),
        ),
    ]
